schema_version: 1

context:
  version: "1.31.190"
  openjdk_min: "11"

package:
  name: verapdf
  version: ${{ version }}

source:
  - url: https://github.com/veraPDF/veraPDF-apps/archive/refs/tags/v${{ version }}.tar.gz
    sha256: 323edfd7860d96996a8883193a1740a8ae009f3298a94d2280137f33d6ec6be3

build:
  number: 0
  script:
    - python ${{ RECIPE_DIR }}/builder.py

requirements:
  build:
    - maven
    - python >=3.11
    - openjdk ${{ openjdk_min }}.*
  run:
    - openjdk >=${{ openjdk_min }}

tests:
  - package_contents:
      strict: true
      bin:
        - verapdf
        - verapdf-gui
      files:
        - etc/conda/test-files/verapdf/**
        - ${{ "share" if unix else "Library" }}/verapdf/**
  - files:
      recipe:
        - Matterhorn-Protocol-1-1.pdf
        - run_test.py
    requirements:
      run:
        - pytest
        - openjdk ${{ openjdk_min }}.*
    script:
      - python run_test.py
  - files:
      recipe:
        - Matterhorn-Protocol-1-1.pdf
        - run_test.py
    requirements:
      run:
        - pytest
    script:
      - python run_test.py

about:
  license: GPL-3.0-or-later OR MPL-2.0
  license_file:
    - LICENSE.GPL
    - LICENSE.MPL
  summary: Command line and GUI industry supported PDF/A and PDF/UA Validation
  homepage: https://github.com/veraPDF/veraPDF-apps
  documentation: https://docs.verapdf.org

extra:
  recipe-maintainers:
    - bollwyvl
